use_frameworks!

target 'ACKategories_Example' do
    pod 'ACKategories', :path => '../'
    
    target 'ACKategories_Tests' do
        inherit! :search_paths
        
        pod 'Quick', '~> 0.9'
        pod 'Nimble', '~> 3.0'
    end
end
