name: Build

on: 
  workflow_call:
  push: 
    branches:
      - main

jobs:
  carthage:
    name: Carthage
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: AckeeCZ/load-xcode-version@1.1.0
      - name: Build
        run: carthage build --no-skip-current --cache-builds --use-xcframeworks
      - uses: actions/cache@v3
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
  spm:
    name: SPM
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: AckeeCZ/load-xcode-version@1.1.0
      - name: Build
        run: swift build -c release
      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-