# https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idname
name: Checks
on:
  pull_request:
    paths:
      - '.swiftlint.yml'
      - 'ACKategories/*.swift'
      - 'ACKategories-Example/*.swift'

jobs:
  swiftlint:
    name: Swiftlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.1.0
  changelog:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Changelog Reminder
        uses: peterjgrainger/action-changelog-reminder@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}