name: Checks

on:
  push:
    tags:
    - '*'

jobs:
  carthage:
    name: Upload Carthage binary 
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 11.4.1
        run: sudo xcode-select -switch /Applications/Xcode_11.4.1.app
  cocoapods:
    name: Push podspec to Cocoapods trunk
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 11.4.1
        run: sudo xcode-select -switch /Applications/Xcode_11.4.1.app
      - name: Install gems
        run: bundle install
      - name: Push podspec
        run: bundle exec pod trunk push --allow-warnings