name: Generate DocC
on:
  push:
    branches: [ main ]
    
jobs:
  Build-Github-Actions:
    runs-on: macos-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Documentation Generation
      run: xcodebuild docbuild -scheme ACKategories -derivedDataPath ./docc -destination 'generic/platform=iOS'
    - name: Update GH Page
      run: (xcrun --find docc) process-archive transform-for-static-hosting ./docc/Build/Products/Debug/ACKategories.doccarchive --hosting-base-path ACKategories --output-path docs;

  
