name: Tests

on: [pull_request, push]

jobs:
  tests:
    name: Run tests
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: AckeeCZ/load-xcode-version@1.1.0
      - name: Run iOS tests
        run: set -o pipefail && xcodebuild test -scheme ACKategories-iOS -resultBundlePath Tests-iOS.xcresult -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15 Pro Max,OS=latest" ONLY_ACTIVE_ARCH=YES | xcpretty
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Tests-iOS.xcresult
          path: Tests-iOS.xcresult
      - name: Run macOS tests
        run: set -o pipefail && xcodebuild test -scheme ACKategoriesCore -resultBundlePath Tests-macOS.xcresult -destination 'platform=OS X,arch=x86_64' | xcpretty
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Tests-macOS.xcresult
          path: Tests-macOS.xcresult