name: Tests

on: [pull_request, push]

jobs:
  tests:
    name: Run tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 11.4.1
        run: sudo xcode-select -switch /Applications/Xcode_11.4.1.app
      - uses: actions/cache@v1
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - name: Install Carthage dependencies
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: carthage bootstrap --platform iOS --cache-builds
      - name: Run iOS tests
        run: set -o pipefail && xcodebuild test -scheme ACKategories-iOS -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.4.1' ONLY_ACTIVE_ARCH=YES | xcpretty
      - name: Run macOS tests
        run: set -o pipefail && xcodebuild test -scheme ACKategoriesCore -destination 'platform=OS X,arch=x86_64' | xcpretty