name: Tests

on: [pull_request, push]

jobs:
  tests:
    name: Run tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Select Xcode 11.4
        run: sudo xcode-select -switch /Applications/Xcode_11.4.app
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - name: Install Bundler
        run: gem install bundler --version 2.1.4
      - name: Install Bundler dependencies
        run: bundle install
      - name: Run iOS tests
        run: set -o pipefail && xcodebuild test -scheme ACKategories-iOS -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.4' ONLY_ACTIVE_ARCH=YES | xcpretty
      - name: Run macOS tests
        run: set -o pipefail && xcodebuild test -scheme ACKategoriesCore -destination 'platform=OS X,arch=x86_64' | xcpretty
      - name: Lint podspec
        run: pod lib lint